services:
  postgres:
    image: docker.io/library/postgres:latest
    container_name: kairo-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kairo

    ports:
      - "5432:5432"

    volumes:
      - kairo-postgres-data:/var/lib/postgresql

volumes:
  kairo-postgres-data:
